Language: 'English'
Prefix: '&7[&dBungeeTeleportManager&7] &r'
Bungee: true
ServerName: 'hub'

UseGlobalPermissionLevel: true #If you wish, that the plugin use the permission level from global
UseServerPermissionLevel: true #If you wish, that the plugin use the permission level from server
UseWorldPermissionLevel: true #If you wish, that the plugin use the permission level from world

ServerClusterActive: false
ServerCluster: 'economyrange' #If you wish, thats multiple Server have the same perm for homes and warps
ServerClusterList:
- hub
WorldClusterActive: false
WorldClusterList:
- hubCluster
- farmweltCluster
hubCluster:
- hubWorld
- hubNether
farmweltCluster:
- farmworld_1
- farmworld_2

Mysql:
  Status: false
  Host: '127.0.0.1'
  Port: 3306
  DatabaseName: 'mydatabase'
  SSLEnabled: false
  AutoReconnect: true
  VerifyServerCertificate: false
  User: 'admin'
  Password: 'not_0123456789'
  TableNameI: 'btmHomes'
  TableNameII: 'btmPortals'
  TableNameIII: 'btmBack'
  TableNameIV: 'btmRespawnPoints'
  TableNameV: 'btmWarps'

isHomesActive: true
isPortalsActive: true
isRespawnPointActive: true
isTeleportsActive: true
isWarpsActive: true

CancelInviteRun: 15 #Scheduler after how many seconds the tp request run out.

BackCooldown: 5 #Second cooldown

DeleteDeathBackAfterUsing: true #Delete DeathBack if it is true

CostPerBackRequest: 100.0
CostPerHomeTeleport: 100.0
CostPerHomeCreate: 1000.0
CostPerTeleportRequest: 100.0
CostPerWarpCreate: 9142.0
MustConfirmWarpWhereYouPayForIt: true
NotifyPlayerWhenUseHome: false  #TODO
NotifyPlayerWhenUseTPA: false  #TODO

ForbiddenServerHome:
- hub
ForbiddenWorldHome:
- hubsworld
ForbiddenServerWarp: #For the Creation
- hub
ForbiddenWorldWarp: #For the Creation
- hubsworld

UploadForbiddenTeleportList: false #If true, so will the server sending the bungeecord the list of forbiddenServer/World for Teleports
ForbiddenServerTeleport: #For tpa and tpahere
- hub
ForbiddenWorldTeleport: #For tpa and tpahere
- hubsworld

# DO NOT CHANGE THINGS BELOW!
# => <origin+message>~click@SUGGEST_COMMAND@/blubb~hover@SHOW_TEXT@messagepath
# => click@SUGGEST_COMMAND@/blubb
# => hover@SHOW_TEXTt@textpath
Identifier:
  Click: 'click'
  Hover: 'hover'
Seperator:
  BetweenFunction: '~'
  WhithinFuction: '@'
  Space: '+'
  HoverNewLine: '~!~'