Language: 'English'
Prefix: '&7[&dBuHoPoReTeWa&7] &r'
ForbiddenServer: false #If true, so will the server sending the bungeecord the list of forbiddenServer/World for Teleports
Bungee: true
ServerName: 'hub'
ServerCluster: 'economyrange' #If you wish, thats multiple Server have the same perm for homes and warps
ServerClusterBeforeServer: false
ServerClusterServerList:
- hub
MustConfirmWarpWhereYouPayForIt: false
Mysql:
  Status: false
  Host: '127.0.0.1'
  Port: 3306
  DatabaseName: 'mydatabase'
  SSLEnabled: false
  AutoReconnect: true
  VerifyServerCertificate: false
  User: 'admin'
  Password: 'not_0123456789'
  TableNameI: 'bhprtwHomes'
  TableNameII: 'bhprtwPortals'
  TableNameIII: 'bhprtwBack'
  TableNameIV: 'bhprtwRespawnPoints'
  TableNameV: 'bhprtwWarps'

CommandArgumentLanguage: 'english' #english, german, both

isHomesActive: true
isPortalsActive: true
isRespawnPoint: true
isTeleportsActive: true
isWarpsActive: true

CancelInviteRun: 15 #Scheduler nach wieviel sekunden die Anfrage ausläuft

CostPerBack: 100.0
CostPerHomeTeleport: 100.0
CostPerHomeCreate: 1000.0
CostPerTeleportRequest: 100.0
CostPerCreateWarp: 9142.0

ForbiddenServerHome:
- hub
ForbiddenWorldHome:
- hubsworld
ForbiddenServerTeleport: #For tpa and tpahere
- hub
ForbiddenWorldTeleport: #For tpa and tpahere
- hubsworld
ForbiddenServerWarp: #For the Creation
- hub
ForbiddenWorldWarp: #For the Creation
- hubsworld

# => <origin+message>~click@SUGGEST_COMMAND@/blubb~hover@SHOW_TEXT@messagepath
# => click@SUGGEST_COMMAND@/blubb
# => hover@SHOW_TEXTt@textpath
Identifier:
  Click: 'click'
  Hover: 'hover'
Seperator:
  BetweenFunction: '~'
  WhithinFuction: '@'
  Space: '+'
  HoverNewLine: '~!~'