Language: 'English'
Prefix: '&7[&dBuHoPoTeWa&7] &r'
Mysql:
  Status: false
  Host: '127.0.0.1'
  Port: 3306
  DatabaseName: 'mydatabase'
  SSLEnabled: false
  AutoReconnect: true
  VerifyServerCertificate: false
  User: 'admin'
  Password: 'not_0123456789'
  TableNameI: 'bhptwHomes'
  TableNameII: 'bhptwPortals'
  TableNameIII: 'bhptwBack'
  TableNameIV: 'bhptwWarps'
isHomesActive: true
isPortalsActive: true
isTeleportsActive: true
isWarpsActive: true
# => <origin+message>~click@SUGGEST_COMMAND@/blubb~hover@SHOW_TEXT@messagepath
# => click@SUGGEST_COMMAND@/blubb
# => hover@SHOW_TEXTt@textpath
Identifier:
  Click: 'click'
  Hover: 'hover'
Seperator:
  BetweenFunction: '~'
  WhithinFuction: '@'
  Space: '+'
  HoverNewLine: '~!~'